SELECT DEVICE, TIME_STAMP, COUNT(TIME_STAMP)
FROM SESSIONS
GROUP BY TIME_STAMP, DEVICE
HAVING COUNT(TIME_STAMP) > 1 LIMIT 25;

SELECT TIME_STAMP FROM SESSIONS
WHERE TIME_STAMP NOT IN (
    SELECT TIME_STAMP FROM SESSIONS
    GROUP BY TIME_STAMP) LIMIT 25;

--4
SELECT HOUR(TIME_STAMP) AS 'DURATION', DEVICE, MAX(Consumption) AS 'PEAK'
FROM SESSIONS
GROUP BY DEVICE, DURATION;

--5
SELECT TIME_STAMP AS 'PEAK'
FROM SESSIONS
WHERE TIME(TIME_STAMP) BETWEEN "09:54:00" AND "15:29:00";

SELECT DEVICE FROM (SELECT HOUR(TIME_STAMP) AS 'DURATION', DEVICE, MAX(Consumption) AS 'PEAK'
FROM SESSIONS
GROUP BY DEVICE, DURATION HAVING DURATION BETWEEN 0 AND 23) AS S GROUP BY DEVICE;

SELECT MAX(HOUR(TIME_STAMP)), DEVICE
FROM SESSIONS
GROUP BY HOUR(TIME_STAMP);
